# noise-free degradations with isotropic Gaussian blurs
#python main.py --dir_data='/home/xingxm/Datasets' \
#               --data_train='DF2K' \
#               --data_test='Set5' \
#               --model='blindsr' \
#               --mode='s-fold' \
#               --scale='2' \
#               --blur_type='iso_gaussian' \
#               --sig_min=0.2 \
#               --sig_max=2.0 \
#               --sig="0.8,0.914,1.03,1.14,1.26,1.37,1.48,1.6" \
#               --n_GPUs=0

#python main.py --dir_data='/home/xingxm/Datasets' \
#               --data_train='DF2K' \
#               --data_test='Set5' \
#               --model='blindsr' \
#               --mode='s-fold' \
#               --scale='3' \
#               --blur_type='iso_gaussian' \
#               --sig_min=0.2 \
#               --sig_max=3.0 \
#               --sig="1.35,1.5,1.65,1.8,1.95,2.1,2.25,2.4" \
#               --n_GPUs=0

#python main.py --dir_data='/home/xingxm/Datasets' \
#               --data_train='DF2K' \
#               --data_test='Set5' \
#               --model='blindsr' \
#               --mode='s-fold' \
#               --scale='4' \
#               --blur_type='iso_gaussian' \
#               --sig_min=0.2 \
#               --sig_max=4.0 \
#               --sig="1.8,2.0,2.2,2.4,2.6,2.8,3.0,3.2" \
#               --n_GPUs=0

#python main.py --dir_data='/home/xingxm/Datasets' \
#               --data_train='DF2K' \
#               --data_test='Set5' \
#               --model='blindsr' \
#               --mode='s-fold' \
#               --scale='2' \
#               --blur_type='aniso_gaussian' \
#               --blur_kernel=11 \
#               --lambda_min=0.6 \
#               --lambda_max=5.0 \
#               --noise=25 \
#               --theta="0,45,90,135,0,45,90,135" \
#               --lambda_1="0.8,0.8,0.8,0.8,2.0,2.0,2.0,2.0" \
#               --lambda_2="1.6,1.6,1.6,1.6,4.0,4.0,4.0,4.0" \
#               --noise_test=15 \
#               --n_GPUs=0

python main.py --dir_data='/home/xingxm/Datasets' \
               --data_train='DF2K' \
               --data_test='Set5' \
               --model='blindsr' \
               --mode='s-fold' \
               --scale='4' \
               --blur_type='aniso_gaussian' \
               --blur_kernel=21 \
               --lambda_min=0.6 \
               --lambda_max=5.0 \
               --noise=25 \
               --theta="0,45,90,135,0,45,90,135" \
               --lambda_1="0.8,0.8,0.8,0.8,2.0,2.0,2.0,2.0" \
               --lambda_2="1.6,1.6,1.6,1.6,4.0,4.0,4.0,4.0" \
               --noise_test=15 \
               --n_GPUs=0